- name: add repo signing keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://swupdate.openvpn.net/repos/repo-public.gpg
    - https://download.docker.com/linux/ubuntu/gpg

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  - deb http://build.openvpn.net/debian/openvpn/stable focal main

- name: add MS repos
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

- name: install apps via repos
  apt:
    update_cache: yes
    name:
    - net-tools
    - docker-ce
    - docker-ce-cli
    - git
    - filezilla
    - vlc
    - powershell
    - openvpn
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - openconnect
    - network-manager-openconnect-gnome
    - network-manager-openconnect

- name: install apps via deb
  apt:
    deb: "{{ item }}"
  with_items:
    - https://github.com/jgraph/drawio-desktop/releases/download/v14.6.13/drawio-amd64-14.6.13.deb
